##日志级别配置
#logging:
#  level:
#    org.springframework.web: ERROR        #Spring框架中的日志级别
#    com.bgd.sparkstreaming: ERROR    #自己项目包名下的日志级别
#
##微信后台参数配置
#wechat:
#  mp:
#    appId:
#    secret:
#    token:
#    aesKey:
